contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Add Layouts To Context
inputs: []
name: Add Layouts To Context
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f8480120-b814-4df9-8826-d12714b03920
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: f8480120-b814-4df9-8826-d12714b03920
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Layout Data
      output:
        simple: ${XSOAR.Layouts}
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Loads certain layout details to the context
      id: 7c312a67-1873-4fae-872c-ff7fece5ec73
      iscommand: false
      name: LoadLayoutsToContext
      scriptName: LoadLayoutsToContext
      type: regular
      version: -1
    taskid: 7c312a67-1873-4fae-872c-ff7fece5ec73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 310
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: XSOAR
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 8ace9efe-64b1-4f96-8d2c-cf7d557f3b2e
      iscommand: false
      name: Delete Existing XSOAR Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8ace9efe-64b1-4f96-8d2c-cf7d557f3b2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 170
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 355,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
