args:
- description: Name of Playbook
  name: playbook_name
  required: true
comment: Retrieves all Playbook (and Sub-Playbook) Names and Integrations for a provided Playbook Name
commonfields:
  id: RetrievePlaybooksAndIntegrations
  version: -1
contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
dockerimage: demisto/python3:3.10.5.31928
enabled: true
name: RetrievePlaybooksAndIntegrations
outputs:
- contextPath: RetrievePlaybooksAndIntegrations.Playbooks
- contextPath: RetrievePlaybooksAndIntegrations.Integrations
runas: DBotWeakRole
runonce: false
script: ''
scripttarget: 0
subtype: python3
tags: []
type: python
fromversion: 6.0.0
tests:
- No tests (auto formatted)
